language: python
python:
- "3.4"
install:
- pip install -r requirements.txt
- python setup.py install
script: 
- python -c "import counterpartylib, apsw, counterpartycli"
- echo "Correctly installed"
